### ISSUE TITLE
Software Requirements Specification

### ISSUE THREAD

**Issue by nsgnn** [ChristopherGerbi/capstone#1]
SRS can be found on our internal shared drive [here](https://drive.google.com/a/maine.edu/file/d/18dhUqbBygx1XeHvjhF9hGmYLvCan_M4g/view?usp=sharing).
Progress on each of these subtasks shall be tracked in the corresponding issue.
- [x] Introduction #2 
- [x] Functional Requirements #3 
- [x] Non-Functional Requirements #4 
- [x] User Interface #5 
- [x] Deliverables #6 
- [x] Open Issues 
  - This section should reflect the main kanban board's `to-do` section.
- [x] Appendix A – Agreement Between Customer and Contractor #7 
- [x] Appendix B – Team Review Sign-off #8 
- [x] Appendix C – Document Contributions #9

**Comment by nsgnn** [comment]
Added the initial draft to `/docs/`. Still awaiting approval from customer
